### PR TITLE
Parameterize comment phrase to trigger a build

### PR DESCRIPTION
**Pull request by nblair**
This pull request makes the comment phrase to trigger a build part of the configuration.

Defaults to "test this please" for backwards compatibility.

### CODE REVIEW

**Comment by nblair** [comment]
Looks like this duplicates pull request #11, which mentions some conflicts.

**Comment by damovsky** [comment]
hi,
can you, please resolve the conflicts? e.g. by rebasing your change, etc...

I'm going to check all PRs and eventually merge them

**Comment by nblair** [comment]
Rebase is finished. I don't have the access to the environment I originally developed this with, so I don't have a way to end to end test the changes, YMMV.

**Comment by nblair** [comment]
I'll see what I can do to get tests passing.

**Comment by damovsky** [comment]
oops, sorry to admit that, but I need you to rebase your change again...looks like in the meantime some change introduce the conflict . Once you rebase it I'll immediately merge it, I promise!

**Comment by nblair** [comment]
Ack, I merged with master to resolve the last conflicts. Would you rather a cherry pick my commits to a new branch and re-submit? Or can I merge with master again?

**Comment by damovsky** [comment]
@nblair it's up to you...what is easy & faster for you? ( the thing is there are many open PRs which I will process in near time and I don't want to bother you again and again with resolving conflicts)

**Comment by nblair** [comment]
Merge was a lot easier than rebase, just pushed.

**Comment by damovsky** [comment]
thank you, @nblair for your help!

**Pull request merged**
