### PR TITLE
Use new Build Status instead of commenting on pull requests

### LINKED ISSUE #65: Support for Bitbucket's new build status API
Bitbucket recently added the build status API for pull requests and branches http://blog.bitbucket.org/2015/11/18/introducing-the-build-status-api-for-bitbucket-cloud/

Could we update this plugin to updating the PR build status instead of leaving comments? The API doc is here https://confluence.atlassian.com/bitbucket/buildstatus-resource-779295267.html

### PR DESCRIPTION
**Pull request by Dahlgren**
News: http://blog.bitbucket.org/2015/11/18/introducing-the-build-status-api-for-bitbucket-cloud/

API: https://confluence.atlassian.com/bitbucket/buildstatus-resource-779295267.html

Fixes #65

### CODE REVIEW

**Comment by brendanator** [comment]
This looks good to me. 

What should ciName and ciKey be set to? This probably needs to go in the README

**Comment by Dahlgren** [comment]
It's used to identify the CI server with Jenkins. key is unique identifier used to match if the commit is already built by the CI server. name is show by the user, as can be seen in the screenshots. I can add them as instructions to the README and as description/help text in the forms. I should be able to update it later tonight.

**Comment by Dahlgren** [comment]
News fields added to README and inline help descriptions added to form for CI Key and CI Name

**Comment by nishio-dens** [comment]
Thank you for your PR.
I'll check it in this weekend.

**Comment by bsideup** [comment]
:+1: looks good

**Comment by bsideup** [comment]
Just tested this change in our (ZeroTurnaround) Jenkins, works great, thanks :) Waiting for it to be merged in upstream

**Comment by nishio-dens** [comment]
umm... I'm trying to check it, but It's not work on my jenkins.

----

my verification procedures

1. PR from https://bitbucket.org/snishio/gitdummywork to https://bitbucket.org/snishio/gitdummy( revision: 11f504f863ac)

procedures_step1

2. Build it, but Bitbucket Build Status API response says "Changeset not found"

procedures_step2

I want someone to tell me if my jenkins setting is mistaken.

**Comment by bsideup** [comment]
@nishio-dens I see that commit hash in BB is truncated compared to commit hash in REST request. But this shouldn't be a problem I think. Weird, because in our environment it works fine. 

Also, your buildUrl in screenshot looks weird. "http:/localhost8080/jenkins"

**Comment by nishio-dens** [comment]
@bsideup 

Oh... thanks. my jenkinsURI settings was wrong. 
(and I change url from http:/localhost8080/jenkins  to http://localhost:8080/jenkins)

but It not work fine.

----

I found a problem this pr.

- PR from https://bitbucket.org/snishio/gitdummy to https://bitbucket.org/snishio/gitdummy (PR to the same repository), It work fine.
- PR from https://bitbucket.org/snishio/gitdummywork to https://bitbucket.org/snishio/gitdummy (Pr to the different repository), It does not work.

**Comment by bsideup** [comment]
@nishio-dens looks like wrong target repo is used in code. We haven't tested this case :)

**Comment by bsideup** [comment]
Just checked code - implementation sends requests against target repo. But it seems that Pull Request statuses should be set in source repo o_O

**Comment by Dahlgren** [comment]
I haven't tested with different repos. I will try to test it and do any corrections during the weekend.

**Comment by Dahlgren** [comment]
I guess this could be an issue if the Bitbucket user account used by Jenkins does not have API write access to the source repository?

**Comment by Dahlgren** [comment]
I guess setting the status on the source repo instead of the target repo at least covers more cases. I'll update the PR.

**Comment by Dahlgren** [comment]
Should work fine for PRs with different target and source repos as long as the Jenkins user has API write access the source repo. I've tested with PRs between two different repos for the same user.

**Comment by tnguyen14** [comment]
@Dahlgren currently the bitbucket user associated with this Jenkins job only has read access to the forked repo that is creating the pull request. This works fine for us. Is there any reason why it now needs write access?

**Comment by Dahlgren** [comment]
Seems to only apply for OAuth usage so it might work fine. I haven't tested this case by myself yet. If you've tried it with the new build status API it should be fine!

**Comment by nishio-dens** [comment]
It works fine, Thanks!

**Comment by nvartolomei** [comment]
When it will be released to Jenkins plugins?

On Saturday, December 12, 2015, S.Nishio <notifications@github.com> wrote:

> It works fine, Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nishio-dens/bitbucket-pullrequest-builder-plugin/pull/66#issuecomment-164115971>
> .
>


-- 
Nicolae Vartolomei, http://nvartolomei.com/

**Comment by Dahlgren** [comment]
Already available!

**Pull request merged**
