### PR TITLE
Removed some v2 regressions that slipped in

### PR DESCRIPTION
**Pull request by CodeMonk**
Specifically in the Bitbucket Server changes

@ChrisLeeTW - Let me know if you saw any others.

### CODE REVIEW

**Comment by chrisLeeTW** [comment]
@CodeMonk I've doned some integration testing with current master + your `CodeMonk:remove-some-v1-endpoints` branch changes, but failed to trigger the build job successfully.

here is main error stacktrace message.
```
Jan 23, 2019 9:55:04 AM warning bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.bitbucket.cloud.CloudApiClient getAllValues
invalid response.
org.codehaus.jackson.map.JsonMappingException: Can not construct instance of bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.bitbucket.AbstractPullrequest$Comment, problem: abstract types can only be instantiated with additional type information
 at [Source: java.io.StringReader@4d7b339; line: 1, column: 29] (through reference chain: bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.bitbucket.Response["values"])
	at org.codehaus.jackson.map.JsonMappingException.from(JsonMappingException.java:163)
	at org.codehaus.jackson.map.deser.StdDeserializationContext.instantiationException(StdDeserializationContext.java:233)
	at org.codehaus.jackson.map.deser.AbstractDeserializer.deserialize(AbstractDeserializer.java:60)
	at org.codehaus.jackson.map.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:217)
	at org.codehaus.jackson.map.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:194)
	at org.codehaus.jackson.map.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:30)
	at org.codehaus.jackson.map.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:299)
	at org.codehaus.jackson.map.deser.SettableBeanProperty$MethodProperty.deserializeAndSet(SettableBeanProperty.java:414)
	at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:697)
	at org.codehaus.jackson.map.deser.BeanDeserializer.deserialize(BeanDeserializer.java:580)
	at org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:2732)
	at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1877)
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.bitbucket.ApiClient.parse(ApiClient.java:193)
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.bitbucket.cloud.CloudApiClient.getAllValues(CloudApiClient.java:105)
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.bitbucket.cloud.CloudApiClient.getPullRequestComments(CloudApiClient.java:34)
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketRepository.isBuildTarget(BitbucketRepository.java:310)
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketRepository.getTargetPullRequests(BitbucketRepository.java:120)
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketPullRequestsBuilder.run(BitbucketPullRequestsBuilder.java:37)
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketBuildTrigger$TriggerRunnable.run(BitbucketBuildTrigger.java:402)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

maybe is it due to the differences for comment response format between bitbucket cloud & bitbucket server ?

**Comment by CodeMonk** [comment]
Looks like last minute changes to #147 broke things severely.

I'd still like to keep the functionality, so I'm debugging and adding some unit tests. Some of the assumptions used in the abstraction made CloudApi (the norm) more difficult. Should have a PR up soon. (Actually, will probably still be this one, with some changes.

**Comment by CodeMonk** [comment]
@chrisLeeTW Could you give it another look, please?

**Comment by chrisLeeTW** [comment]
@CodeMonk sorry for delay reply. I've doned integration testing again, and It's works as expected for main feature. Nice works. 👍

**Pull request merged**
