### PR TITLE
Add support for credentials from the Jenkins credentials store

### PR DESCRIPTION
**Pull request by kadaan**
Support credentials by allowing UsernamePasswordCredentials to be picked when configuring BitbucketBuildTrigger and changed BitbucketRepository to use the credentials when setting up the ApiClient.

Closes: Add support for Credentials plugin #33

### CODE REVIEW

**Comment by jawshooah** [comment]
This update would break existing installations, correct? Might it be better to keep plaintext as an insecure alternative?

**Comment by kadaan** [comment]
Explain how it can be kept as in alternative.

**Comment by jawshooah** [comment]
It absolutely shouldn't remain the default, but it could be an option. I'm not familiar with the Jenkins plugin API, so I have no suggestions for actual implementation, but in the UI you could have a radio button with the Credentials plugin as one option (the default), and plaintext as the other. Not sure how this would work with existing configurations, though.

**Comment by kadaan** [comment]
Since I'm not really good with jelly, I just put the old username and password fields back. If credentials are not picked from the drop-down then the username and password fields are used.

**Comment by kadaan** [comment]
Can someone please review this?

**Comment by jawshooah** [comment]
Amen. #65 and #67 have been crazy active recently, but no love for this (IMO much more important) PR.

**Comment by Dahlgren** [comment]
Yes, this is much needed. It's very annoying that credentials needs to be entered for every job.

**Comment by pdjtrifork** [comment]
Yes, we need a review (and merge) for this one. It IS important for sure. Would be nice to get rid of the basic auth for this specific plugin when others are using credentials

**Comment by kadaan** [comment]
Who can do the review?

**Comment by kadaan** [comment]
Bueller?

**Comment by jawshooah** [comment]
@nishio-dens - much :heart: if you'll at least give this a review!

**Comment by kadaan** [comment]
@nishio-dens Could you please review this?

**Comment by nishio-dens** [comment]
I'm so sorry for my late response. I'll check #74 and #64  in this weekend.

**Comment by kadaan** [comment]
Thanks!

**Comment by nishio-dens** [comment]
I merged #74 .

**Pull request closed without merging**
