### PR TITLE
Adapt to SECURITY-170

### PR DESCRIPTION
**Pull request by frodeaa**
Use EnvironmentContributor instead of build parameters 

Based on https://github.com/jenkinsci/ghprb-plugin/pull/344

Fixes: #86

### CODE REVIEW

**Comment by maxvodo** [comment]
@nishio-dens, @frodeaa Looks good

**Comment by saada** [comment]
Can anybody test this?

**Comment by frodeaa** [comment]
I have tested it and it works, but it has the problem that a lot of empty "Parameters" links are added to each build

screen shot 2016-05-25 at 17 07 35

**Comment by frodeaa** [comment]
I believe the fix in https://github.com/jenkinsci/ghprb-plugin/pull/351/commits/baee0e392521a957a914c2fa022abf06a2ace2e0 will solve it

**Comment by frodeaa** [comment]
5485845edafde360cd43f035ca329cfe3baba49a fixes the issue with many "Parameters" links

**Comment by houmie** [comment]
Great! Thanks guys. Hopefully it can be released soon.

**Comment by houmie** [comment]
Guys, what is the process for this to get released? This blocks the whole plugin to function, so its quite urgent.

**Comment by tnguyen14** [comment]
Please help with releasing this. I tried downgrading my Jenkins from 2.x back to 1.651 to temporarily fix this, but I'm still getting this same error. I wonder if this has to do with the fact that some data might have been migrated when updating to 2.x and it's no longer backward compatible?

**Comment by frodeaa** [comment]
@tnguyen14 you can while waiting for the release just build the plugin, upload and install it in your jenkins instance.

**Comment by tnguyen14** [comment]
@frodeaa you mean building off of your `frodeaa:security-170-patch` branch?

**Comment by YANOUSHek** [comment]
You can also whitelist the params used by this plugin passing this when starting Jenkins:
```
-Dhudson.model.ParametersAction.safeParameters=targetBranch,sourceBranch,repositoryOwner,repositoryName,pullRequestId,pullRequestTitle,destinationRepositoryOwner,destinationRepositoryName
```

**Comment by frodeaa** [comment]
@tnguyen14 yes build it off my branch

**Comment by nishio-dens** [comment]
I'm sorry for my late response.
thanks!

**Comment by houmie** [comment]
Hey thanks, when can we expect a release? 💃

**Comment by nishio-dens** [comment]
I have released version-1.4.19 including this PR fix.
https://wiki.jenkins-ci.org/display/JENKINS/Bitbucket+pullrequest+builder+plugin

**Comment by houmie** [comment]
Many thanks, But i still see only 1.4.18. Maybe it takes longer to populates across the globe...

**Comment by saada** [comment]
Like a charm!

**Comment by DoDoENT** [comment]
OK, I've added the whitelist, yet value of sourceBranch variable is still 'master' in my case - however correct commit is being built. This confuses me. I use 'sourceBranch' variable to set the build name and to pass on the source branch to another job which. Is there a way to access 'sourceBranch' variable outside of plugin? I've tried using GIT_BRANCH variable for my needs, but it is set to 'origin/master' (I use merge before build). Is there any alternative?

Please advise.

**Comment by frodeaa** [comment]
@DoDoENT I have just tested a job triggered by pull request and ```sourceBranch``` is set and available in the build command shell

Are you using the variable elsewhere?

**Comment by frodeaa** [comment]
I suspect we need to implement QueueAction as done in https://github.com/jenkinsci/matrix-project-plugin/commit/d9e5c847afef3928441bdb91df37f764ea6617fd to make the build parameters available in child jobs

**Comment by DoDoENT** [comment]
@frodeaa, my job has parameter named `sourceBranch`. This parameter can be set manually when triggering job or is set by Bitbucket pull request builder plugin. Default value of the parameter is `master`. After echoing the value of `sourceBranch` inside command shell, the value echoed is `master`.

**Comment by DoDoENT** [comment]
Btw, I am using MultiJob project to spawn child jobs and those child jobs should inherit `sourceBranch` parameter.

**Comment by hjeong1114** [comment]
I installed 1.4.19 on jenkins 2.10, but the parameters are not replaced by the values. The fix doesn't require whitelisting of the parameters correct? What am I missing?

```
Cloning the remote Git repository
Cloning repository git@bitbucket.org:${repositoryOwner}/${repositoryName}.git
 > git init /var/lib/jenkins/workspace/backend-develop-PR # timeout=10
Fetching upstream changes from git@bitbucket.org:${repositoryOwner}/${repositoryName}.git
 > git --version # timeout=10
 > git -c core.askpass=true fetch --tags --progress git@bitbucket.org:${repositoryOwner}/${repositoryName}.git +refs/heads/*:refs/remotes/origin/*
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Command "git -c core.askpass=true fetch --tags --progress git@bitbucket.org:${repositoryOwner}/${repositoryName}.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
stdout: 
stderr: conq: invalid command syntax.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1719)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1463)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:63)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:314)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:506)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1057)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1097)
	at hudson.scm.SCM.checkout(SCM.java:495)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1269)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:604)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)
	at hudson.model.Run.execute(Run.java:1720)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
ERROR: null
```

**Pull request merged**
