### PR TITLE
a few properties have changed their name

### PR DESCRIPTION
**Pull request by cocorossello**
Fixed the NPE caused by a few Comment properties that have changed their name 

Changes from
https://github.com/nishio-dens/bitbucket-pullrequest-builder-plugin/pull/106

### CODE REVIEW

**Comment by jkobus** [comment]
documentation did not change:
https://confluence.atlassian.com/bitbucket/pullrequests-resource-1-0-296095210.html#pullrequestsResource1.0-POSTanewcomment

Are you sure these fields have different names now? That would violate the bitbucket's backward-compatibility policy.

**Comment by cocorossello** [comment]
The plugin is using the V2 API, not the V1. 

I can't find the comment object in the V2 doc myself, but just check the response.

Searching pull request comments for a random public repository:

https://api.bitbucket.org/2.0/repositories/sdorra/scm-jenkins-plugin/pullrequests/1/comments

(this pull request: https://bitbucket.org/sdorra/scm-jenkins-plugin/pull-requests/1/added-support-for-multiple-projects/diff )

The json object for a commit is:

{
      "links": {
        "self": {
          "href": "https://api.bitbucket.org/2.0/repositories/sdorra/scm-jenkins-plugin/pullrequests/1/comments/10479140"
        },
        "html": {
          "href": "https://bitbucket.org/sdorra/scm-jenkins-plugin/pull-requests/1/_/diff#comment-10479140"
        }
      },
      "pullrequest": {
        "type": "pullrequest",
        "id": 1,
        "links": {
          "self": {
            "href": "https://api.bitbucket.org/2.0/repositories/sdorra/scm-jenkins-plugin/pullrequests/1"
          },
          "html": {
            "href": "https://bitbucket.org/sdorra/scm-jenkins-plugin/pull-requests/1"
          }
        },
        "title": "* Added support for multiple projects."
      },
      "content": {
        "raw": "It is possible that you resubmit the pull request, without the indent and import changes? Because i can't see the real changes.",
        "markup": "markdown",
        "html": "<p>It is possible that you resubmit the pull request, without the indent and import changes? Because i can't see the real changes.</p>"
      },
      "created_on": "2015-10-04T16:36:44.661571+00:00",
      "user": {
        "username": "sdorra",
        "display_name": "Sebastian Sebastian",
        "type": "user",
        "uuid": "{730e4ff6-fc2a-4f77-9cba-91b89f3760d9}",
        "links": {
          "self": {
            "href": "https://api.bitbucket.org/2.0/users/sdorra"
          },
          "html": {
            "href": "https://bitbucket.org/sdorra/"
          },
          "avatar": {
            "href": "https://bitbucket.org/account/sdorra/avatar/32/"
          }
        }
      },
      "updated_on": "2015-10-04T16:36:44.668030+00:00",
      "type": "pullrequest_comment",
      "id": 10479140
    }

**Comment by jkobus** [comment]
You are right. I checked the response myself and it indeed changed.
Call is made from ApiClient.java:99.

**Comment by osrufung** [comment]
Hi! any idea about when this release will be public on the Jenkins repo? https://wiki.jenkins-ci.org/display/JENKINS/Bitbucket+pullrequest+builder+plugin

**Comment by osrufung** [comment]
I'm getting this error on the 1.4.23 

> bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketBuildTrigger.run() failed for hudson.model.FreeStyleProject@421c393f[iOS_PR_builder]
java.lang.NullPointerException
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.bitbucket.Pullrequest$Comment.compareTo(Pullrequest.java:196)
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.bitbucket.Pullrequest$Comment.compareTo(Pullrequest.java:184)
	at java.util.ComparableTimSort.countRunAndMakeAscending(ComparableTimSort.java:320)
	at java.util.ComparableTimSort.sort(ComparableTimSort.java:188)
	at java.util.Arrays.sort(Arrays.java:1312)
	at java.util.Arrays.sort(Arrays.java:1506)
	at java.util.ArrayList.sort(ArrayList.java:1454)
	at java.util.Collections.sort(Collections.java:141)
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketRepository.filterPullRequestComments(BitbucketRepository.java:204)
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketRepository.isBuildTarget(BitbucketRepository.java:246)
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketRepository.getTargetPullRequests(BitbucketRepository.java:94)
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketPullRequestsBuilder.run(BitbucketPullRequestsBuilder.java:37)
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketBuildTrigger.run(BitbucketBuildTrigger.java:272)
	at hudson.triggers.Trigger.checkTriggers(Trigger.java:272)
	at hudson.triggers.Trigger$Cron.doRun(Trigger.java:221)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:50)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by damovsky** [comment]
@osrufung this has been fixed in 1.4.24, released a few minutes ago

**Comment by osrufung** [comment]
More errors con 1.4.24 version


> java.io.EOFException: No content to map to Object due to end of input
	at org.codehaus.jackson.map.ObjectMapper._initForReading(ObjectMapper.java:2775)
	at org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:2718)
	at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1877)
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.bitbucket.ApiClient.parse(ApiClient.java:275)
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.bitbucket.ApiClient.getAllValues(ApiClient.java:206)
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.bitbucket.ApiClient.getPullRequests(ApiClient.java:105)
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketRepository.getTargetPullRequests(BitbucketRepository.java:91)
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketPullRequestsBuilder.run(BitbucketPullRequestsBuilder.java:37)
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketBuildTrigger.run(BitbucketBuildTrigger.java:272)
	at hudson.triggers.Trigger.checkTriggers(Trigger.java:272)
	at hudson.triggers.Trigger$Cron.doRun(Trigger.java:221)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:50)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by cocorossello** [comment]
This doesn't have to be merged, it was fixed in another way. I'm going to close the PR since it makes no sense, sorry for not doing it earlier

**Pull request closed without merging**
