### PR TITLE
Continuously rebuilding and filter for building pull requests to specific branch 

### PR DESCRIPTION
**Pull request by maxvodo**
This pull request avoid continuously rebuilding for projects, when comment `test this please` on the bit bucket pull requests thread there. Also you can use filter field to specify for your project, which of branches (sources or destinations) Jenkins will be build for each pull request.

Similar issues: #61  and #62.

### CODE REVIEW

**Comment by maxvodo** [comment]
Also, pull request comment thread may contain many `test this please` comment. Plugin check only last `test this please` comment and decides to trigger build or not.

Suppose, we have comments (old comment below):

* Jenkins: test this please
* TTP build flag `[bid: #jenkins-902f259e962ff16100843123480a0970]`

Jenkins won't trigger build if `#jenkins-902f259e962ff16100843123480a0970` build already builded. But, if you wrote new `test this please` comment, like that:

* Jenkins: test this please
* TTP build flag `[bid: #jenkins-902f259e962ff16100843123480a0970]`
* Jenkins: test this please

Jenkins rebuild project with buildid=bid `#jenkins-902f259e962ff16100843123480a0970` and comments thread  show like that:

* Jenkins: test this please
* TTP build flag `[bid: #jenkins-902f259e962ff16100843123480a0970]`
* Jenkins: test this please
* TTP build flag `[bid: #jenkins-902f259e962ff16100843123480a0970]`

Huh... :smile:

**Comment by nishio-dens** [comment]
Thanks you so much. It's work fine and I merge it.

**Comment by tnguyen14** [comment]
thanks @nishio-dens. will there be a real version release soon?

**Comment by nishio-dens** [comment]
@tnguyen14 yes, my mission was completed. I released it. (as ver 1.4.13)
https://wiki.jenkins-ci.org/display/JENKINS/Bitbucket+pullrequest+builder+plugin

**Comment by pdjtrifork** [comment]
Cool, thanks. This update fixes our previous issues from release 1.4.8 (the TTP issue), so now we can also enjoy the support for Bitbucket Build Status :)

**Pull request merged**
