### PR TITLE
Add ability to insert comment from file.

### PR DESCRIPTION
**Pull request by Sanchiz**
Currently BitBucket pull request builder allows add only link to Jenkins job. I've added implementation which allows you specify file as source for new comment.

image

In the Jenkins job you can write any data to file and this will be in comment on BitBucket.

```
phpcs --standard=Zend ./includes/path.inc > ${WORKSPACE}/comment.md
```

### CODE REVIEW

**Comment by killerwolf** [comment]
+1

**Comment by podarok** [comment]
+1

**Comment by damovsky** [comment]
@Sanchiz could you, please, resolve the conflicts? i.e. by rebasing ? this PR looks very interesting

**Comment by damovsky** [comment]
@Sanchiz oh, wait...there is one thing I don't understand....why you want to write the comment in some file? what about using some environment variable ? 

what I don't want is to make configuration of this plugin too complicated and here I'm not sure if everyone understand your motivation. When I firstly saw the screenshot with configuration option "Comment file path" I did not get the point...my questions were like: "why should I specify some comment file ? and what is it used for? what kind of comment is / will be in the file? etc."

**Comment by CodeMonk** [comment]
@Sanchiz Are you still interested in this change? If not, I will close the PR.

**Comment by CodeMonk** [comment]
Closing. Please re-submit if you want it in in the future.

**Pull request closed without merging**
