### PR TITLE
Closed #89 Added Bitbucket server Url configuration

### LINKED ISSUE #89: Bitbucket Server
Currently it is based on the bitbucket.org service and cannot connect to a Bitbucket server API since the endpoint and the domain are differents.

It would be great to have an option to add a Bitbucket server endpoint url to override the hardcoded endpoint.

More info here: https://developer.atlassian.com/bitbucket/server/docs/latest/how-tos/command-line-rest.html

### PR DESCRIPTION
**Pull request by jeremyFreeAgent**

### CODE REVIEW

**Comment by jeremyFreeAgent** [comment]
That should fixe #89 but I can build the hpi file with `nvm install` command.

**Comment by jeremyFreeAgent** [comment]
I saw that the payloads are different. Need work on the PullRequest object.

**Comment by damovsky** [comment]
hi @jeremyFreeAgent, I'm a new maintainer of this project. 

I don't understand what is this PR about. Why you'd like to configure bitbucket server url? it's already in main jenkins configuration, isn't it?

**Comment by CodeMonk** [comment]
@jeremyFreeAgent Are you still interested in this change? If not, I'll close the PR.

**Comment by CodeMonk** [comment]
Closing PR - if you need this in the future, please re-submit.

**Pull request closed without merging**
