### PR TITLE
Fixes the error when posting build status and adds logs

### PR DESCRIPTION
**Pull request by ghusse**
Fixes the error 

```
POST state INPROGRESS to https://bitbucket.org/api/2.0/repositories/null/null/commit/5fa518995d69/statuses/build with key jenkins-85ed65ec66bdc0537a94b1dfd4eb7b54 with response {"type": "error", "error": {"message": "Repository null/null not found"}}
```

This PR is base on the code from 1.4.19, not master, because master seems to be broken.

Bitbucket does not seem to return the repository owner & name in previous responses. Instead, I propose to use values directly from the plugin configuration.

This bug causes Jenkins to build **every repository** in loop because it cannot set their state.

### CODE REVIEW

**Comment by ghusse** [comment]
This PR also adds more detailed logging when the api client is unable to parse response.

This kind of logging is very useful to know what happens, for instance you're now able to read that your *Rate Limit* had exceeded.

**Comment by ghusse** [comment]
PR updated to use names from the configuration in another place.

I'm not sure it will work with PR from external repositories

**Comment by garrethmcdaid** [comment]
Instructions to build and install locally:

git clone https://github.com/ghusse/bitbucket-pullrequest-builder-plugin.git
cd bitbucket-pullrequest-builder-plugin
mvn compile hpi:hpi

This will create bitbucket-pullrequest-builder.hpi in ./target

You can then move the hpi file to $JENKINS_HOME/plugins and restart Jenkins

I also removed the existing plugin files before doing this

Thanks to @ghusse

**Comment by despairblue** [comment]
Instead of moving it to a folder in the server it can also be uploaded from the web ui: $JENKINS_URL/pluginManager/advanced .

**Comment by despairblue** [comment]
Oh and it does work. Thanks @ghusse 🙇

**Comment by ghusse** [comment]
On our server Jenkins does not stop looping on the same builds... It seems to be another issue.

**Comment by ghusse** [comment]
The last modification seem to completely fix the issue.

Just to be clear: this correction works for us and fixes the issue in the very short term. But I'm pretty sure it won't work with pull request made from forks.

**Comment by jkobus** [comment]
"test this please" feature also works. jenkins is quiet now, not repeating builds. thanks @ghusse.

**Comment by garrethmcdaid** [comment]
Can confirm that issue is resolved for us too.

**Comment by jkobus** [comment]
Its worth to notice, that after restart jenkins queue might still contain wrongly configured builds and all should be canceled. Plugin update will not fix them.

**Comment by cocorossello** [comment]
Issue resolved for us. Thanks!

**Comment by alucardzom** [comment]
This doesn't work for us, we have a NullPointerException error when are ordering pull requests:
`java.lang.NullPointerException
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.bitbucket.Pullrequest$Comment.compareTo(Pullrequest.java:193)
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.bitbucket.Pullrequest$Comment.compareTo(Pullrequest.java:184)
	at java.util.ComparableTimSort.countRunAndMakeAscending(ComparableTimSort.java:290)
	at java.util.ComparableTimSort.sort(ComparableTimSort.java:157)
	at java.util.ComparableTimSort.sort(ComparableTimSort.java:146)
	at java.util.Arrays.sort(Arrays.java:472)`

**Comment by christcake** [comment]
I am also seeing the same NPE as @alucardzom above. Has anyone had a chance to look into this?

**Comment by perzonaljezus** [comment]
Same problem here.
When will the fixes be merged?
I don't want to build the jpi locally.

**Comment by jkobus** [comment]
If anyone have problems with building this plugin, here is the hpi file, built by me, that can be used:
http://s000.tinyupload.com/index.php?file_id=09461224743201830697

Its a temporary solution of course.

**Comment by perzonaljezus** [comment]
Thank you, but I'm more or less just a user of Jenkins.

What happens when the hpi file is copied to $JENKINS_HOME/plugins and restart Jenkins?

I only can find plugins/bitbucket-pullrequest-builder.jpi and the directory plugins/bitbucket-pullrequest-builder/.

Will Jenkins on startup  process the hpi file and recreate the jpi file and the plugins/bitbucket-pullrequest-builder/ directory etc? 
Should I remove the plugins/bitbucket-pullrequest-builder/  first (as @garrethmcdaid commented)?

**Comment by ghusse** [comment]
You can install it directly from the web interface, as @despairblue noted:

> Instead of moving it to a folder in the server it can also be uploaded from the web ui: $JENKINS_URL/pluginManager/advanced .

**Comment by perzonaljezus** [comment]
Thanks a lot!
It worked.

**Comment by jkobus** [comment]
@ghusse when I have only one job enabled using this plugin it works. It does not duplicate builds. Enabling another job makes the plugin go crazy again :)

**Comment by ghusse** [comment]
@jkobus did you configure both jobs on the same repo? If that's the case, you must change the CI Identifier in your second job.

We have more than 20 jobs using this plugin, and everything is working great.

**Comment by ccamp46** [comment]
Will this build work with pipelines?  I am afraid to downgrade.. I am using "1.4.20-SNAPSHOT (private-754a250e-frode)"

**Comment by ghusse** [comment]
I don't know what changed in the version you're using, I suppose it is not an official version.

**Comment by arcadien** [comment]
I no longer have the null/null issue, but a : 
`java.lang.AssertionError: class bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketBuildTrigger is missing its descriptor`
In Jenkins log.

**Comment by aabed** [comment]
I've applied the fix, the loop stopped but the PRs also stopped triggering a build

**Comment by cocorossello** [comment]
Check this pull request https://github.com/nishio-dens/bitbucket-pullrequest-builder-plugin/pull/107

**Comment by aabed** [comment]
@cocorossello Thanks, it worked

**Comment by damovsky** [comment]
hi @ghusse , if you resolve the conflict, I can merge your PR....

**Comment by CodeMonk** [comment]
While I like some of the more verbose logging in this PR, I think most of the issues have been fixed in other prs, so, without an update, I'm closing this.

Please feel free to re-submit if I missed anything.

**Comment by CodeMonk** [comment]
Fixed in #165

**Pull request closed without merging**
