### PR TITLE
[Fixes #137] Move from basic auth (which no longer appears to work) to OAuth

### LINKED ISSUE #137: Failure authenticating with BASIC 'Bitbucket.org HTTP'@bitbucket.org:443
I have a problem with jenkins and bitbucket
WARNING: invalid response.

but if disable credentialsId and login with username & password: just getting an error WARNING: invalid response.

Using jenkins 2.7.3
Pipeline from SCM and proporties
    pipelineTriggers([
        bitbucketpr(
        approveIfSuccess: true,
        branchesFilterBySCMIncludes: true,
        cancelOutdatedJobs: false,
        checkDestinationCommit: false,
        ciKey: 'jenkins',
        ciName: 'Jenkins',
        ciSkipPhrases: '', 
        commentTrigger: 'test this triger please', 
        credentialsId: '', 
        cron: '* * * * *', 
        password: 'username', 
        repositoryName: 'reponame', 
        repositoryOwner: 'ownerRepo', 
        username: 'user@mail.com')
    ]),

### PR DESCRIPTION
**Pull request by Remboooo**
Allows you to create Jenkins credentials for a team rather than a user.

### CODE REVIEW

**Comment by ip1981** [comment]
This does not make sense. Oauth2 assumes human interaction, but basic authentication still works, you just need an "application password", not regular user password.

**Comment by Remboooo** [comment]
I could not get the application password to work; it kept giving the failure in the linked issue. These changes fixed the issue for me.

OAuth2 is definitely not only for human interaction; if you go to your bitbucket settings there is a section 'OAuth' that allows you to manage 'OAuth integrated applications'. This is the mechanism this PR intends to use. You click the 'add consumer' button there and it generates a key and secret, which you add to Jenkins as user/password credentials. Then you select those credentials in build config for this plugin.

It's the same mechanism as used by the bitbucket build status notifier (https://github.com/jenkinsci/bitbucket-build-status-notifier-plugin) which this PR borrows two classes from. What's nice is that this now allows you to use a single set of credentials for both plugins.

That said, I'm not happy about the quality of this PR yet; it was basically a quick fix for a problem I was having. I'm happy to either keep it internal to us or close it until I get around to improving the quality, i.e. not retrieving a new token for each request, and re-adding relevant unit tests.

**Comment by ip1981** [comment]
Did you check it out with curl?
`curl https://USER:PWD@bitbucket.org/api/2.0/repositories/ANOTHER-USER`

Maybe we are talking about the same thing, but I've [been using](https://github.com/ip1981/bbprb) "application" passwords since last year without any problems. And I am sure I never open OAuth section. Maybe app's permissions aren't good?

**Comment by CodeMonk** [comment]
@Remboooo Are you still interested in getting something into the codebase? 

We're trying to release soon, and this PR would be considered if it were updated, and the conflicts fixed.

Thanks in advance,

-Dave

**Comment by CodeMonk** [comment]
Closing due to inactivity / lack of response.

**Pull request closed without merging**
