### PR TITLE
ApiClient and Pullrequest refactored to support both Cloud and Server…

### PR DESCRIPTION
**Pull request by pedrohrr**
I made a lot of refactoring in a lot of files.
Please validate if I made any mess in your code. 
Glad I could help

### CODE REVIEW

**Comment by topera** [comment]
I'd like to use this feature also.

**Comment by CodeMonk** [comment]
@pedrohrr , I'd love to get this change in - several people would like this to work with server as well as cloud.

Would you have any time to update it and remove the conflicts so we can get it into the next release?

-Dave

**Comment by pedrohrr** [comment]
Sorry for taking so long, there is no more conflicts.

**Comment by CodeMonk** [comment]
```
[INFO] Dead store to destinationCommitHash in bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketRepository.isFilteredBuild(AbstractPullrequest) [bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketRepository] At BitbucketRepository.java:[line 357] DLS_DEAD_LOCAL_STORE
[INFO] bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.bitbucket.server.ServerPullrequest$Comment defines compareTo(Object) and uses Object.equals() [bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.bitbucket.server.ServerPullrequest$Comment] At ServerPullrequest.java:[line 184] EQ_COMPARETO_USE_OBJECT_EQUALS
[INFO] 
```

**Comment by CodeMonk** [comment]
```[INFO] bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.bitbucket.server.ServerPullrequest$Comment defines compareTo(Object) and uses Object.equals() [bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.bitbucket.server.ServerPullrequest$Comment] At ServerPullrequest.java:[line 184] EQ_COMPARETO_USE_OBJECT_EQUALS```

**Comment by CodeMonk** [comment]
@pedrohrr Let me know if you need any help with the most recent fix. I'm just copying the logs from drilling down into the build, by clicking on `Details` on the failure, then getting down to a particular failed build, then the logs.

Let me know!

**Comment by pedrohrr** [comment]
I did see this issue, but I'm not sure if this should be treated as such. It seems to me more like a problem with findbugs analysis on this case. But I've rolled back the implementation for the comparable to correct it

**Pull request merged**
